spring:
  jackson:
    default-property-inclusion: non_empty
  # 数据库配置
  datasource:
    url: jdbc:mysql://192.168.1.128:3306/security-mybatis-plus?useUnicode=true&characterEncoding=utf8&useSSL=false
    # 用户名
    username: root
    # 密码
    password: 123456
    # 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis-plus https://mp.baomidou.com/config
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_null
      update-strategy: not_null
      # 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 开启自动驼峰命名规则映射 表字段名`A_B`映射为Java属性`aB`
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/example/mapper/*.xml
  type-aliases-package: com.example.model
