spring:
  jackson:
    # Jackson 只能指定 Date 序列化格式，LocalDateTime 需要手动配置
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_empty
# 自定义变量
lilei:
  # 令牌验证
  token:
    enabled: true
  # 记录日志
  log:
    enabled: true
  # 参数签名验证
  sign:
    enabled: true
    salt: LILEI
