spring:
  jackson:
    date-format: yyyy年MM月dd日 HH时mm分ss秒
    # 在spring-boot2前 返回json数据 时间会自动转换为时间戳 2以后需要手动配置
    # serialization:
      # write-dates-as-timestamps: true
    time-zone: GMT+8
    # 参数意义
    # JsonInclude.Include.ALWAYS 默认不生效                  序列化
    # JsonInclude.Include.NON_NULL 属性为NULL               不序列化
    # JsonInclude.Include.NON_DEFAULT  属性为默认值         序列化
    # JsonInclude.Include.NON_ABSENT 属性为空字符串          不序列化
    # JsonInclude.Include.NON_EMPTY 属性为空字符串 或 NULL   不序列化
    # JsonInclude.Include.NON_DEFAULT 属性为默认值时         不序列化
    # JsonInclude.Include.CUSTOM 指定自定义筛选器            不序列化
    # JsonInclude.Include.USE_DEFAULTS 使用类或对象的默认值   序列化
    default-property-inclusion: ALWAYS